### ISSUE TITLE
Learn JS and TS

### ISSUE THREAD

**Issue by atltt** [utk-cs/team-minsky#11]
Two of us have not used these languages. 

CodeAcademy away!

**Comment by RexRascerX** [comment]
var issue = {
  name : "Jonathan Bueckman",
  status : "Learning",
  JavaScriptLearned : true,
  TypeScriptLearned : false
}

**Comment by RexRascerX** [comment]
interface Programmer {
  name: string;
  JavaScriptKnowledge: boolean;
  TypeScriptKnowledge: boolean;
  thoughts: string;
}
var Prog1 = {
  name: "Jonathan Bueckman";
  JavaScriptKnowledge: true;
  TypescriptKwnoledge: true;
  thoughts: "Not a master, but confident enough to close the issue";
}

**Comment by robobenklein** [comment]
@atltt ready to roll?
