### ISSUE TITLE
Make a Wrapper class in TypeScript to make it more convenient to access stuff from Octokit

### ISSUE THREAD

**Issue by ilumsden** [utk-cs/team-minsky#18]
I think we should have a wrapper class to make it easier to access functions from Octokit.

**Comment by robobenklein** [comment]
We will also need a common layer for accessing issues from both Gitlab and Github, so this should be an abstraction at the same time.

**Comment by ilumsden** [comment]
I'm making this comment to associate my commits with this issue:
1d9c301, 79a1de5, 4a0f69d, 844a23a, b2a3d51, 1f00dfc

**Comment by robobenklein** [comment]
Pro tip: it's always easier to reference the issue from the commit.

You can also put the issue tag in the below-the-fold of the commit message (two newlines after the first) and it will still link.
