### ISSUE TITLE
Research existing Atom plugins written in TypeScript

### ISSUE THREAD

**Issue by ilumsden** [utk-cs/team-minsky#19]
We need to figure out how to best set up the plugin so that we can use TypeScript.

An example package is [here](https://github.com/TypeStrong/atom-typescript).

**Comment by ilumsden** [comment]
We'll need to have a `tsconfig.json` file to configure `tsc` options. [Here's](https://github.com/TypeStrong/atom-typescript/blob/master/lib/tsconfig.json) an example.

**Comment by ilumsden** [comment]
It should be in `lib`

**Comment by robobenklein** [comment]
`atom-typescript` is MIT so I'm gonna copy some scaffolds from there.

**Comment by ilumsden** [comment]
I mentioned this in #24. I'm just copying it here:

The way I see it, the only change with TypeScript is with the lib and dist directories. With JavaScript, you'd usually have your source code in lib, and package.json would use lib for the immediate functionality. With TypeScript, you need the intermediate transpilation to JavaScript (which outputs to dist), and then package.json uses the transpiled JavaScript for immediate functionality.

**Comment by robobenklein** [comment]
We will now need to develop an empty main for atom to hook into and try it out so if it loads as an atom plugin. That should finish #8

**Comment by robobenklein** [comment]
![image](https://user-images.githubusercontent.com/5423266/46694310-6b66ac00-cbda-11e8-8880-4483a93612c9.png)

`atom-typescript` is doing some weird things here.

Looks like loading .ts files?

**Comment by robobenklein** [comment]
I think we're safe to say we understand the Typescript differences now.
