### ISSUE TITLE
Make some Waffles

### ISSUE THREAD

**Issue by robobenklein** [utk-cs/team-minsky#2]
Because they are better than pancakes.

https://waffle.io/

**Comment by robobenklein** [comment]
I think we are liking the Waffles, they are tasty. If @atltt @ilumsden or @RexRascerX  agree, this issue is done. (Close it.)

**Comment by ilumsden** [comment]
I agree. @atltt? @RexRascerX?

**Comment by ilumsden** [comment]
I'm saying we're good on this. Closing.
