### ISSUE TITLE
Implement the GitHub Issue and PR classes

### ISSUE THREAD

**Issue by ilumsden** [utk-cs/team-minsky#51]
The interfacing for GitHub/GitLab Issues and Pull/Merge Requests is now done. The next step is implementing these API wrappers for GitHub.

**Comment by ilumsden** [comment]
Forgot to link bde30d2 here.

**Comment by robobenklein** [comment]
I have personally seen the Issue class working in production...

**Comment by ilumsden** [comment]
The PR class might take a little longer than expected. I'm running into the Diamond Problem in my inheritance, and figuring out how to resolve it is proving tricky.
