### ISSUE TITLE
Make an Action command.

### ISSUE THREAD

**Issue by RexRascerX** [utk-cs/team-minsky#52]
The code needs to do something upon user command.

**Comment by robobenklein** [comment]
What active commands should we add?

I can't think of too much use for the command palette for our primary use case, but I expect there should be some.

Perhaps:

"Open issue ID under cursor" which fetches the regex and finds which one the text cursor is currently on and opens that one?

**Comment by RexRascerX** [comment]
This was mostly to let anyone manually run their code in Atom to see it work or how it doesn't work. I could try adding a passive function to it to see how they work, but I assumed we wanted something to test with.

**Comment by robobenklein** [comment]
Merged with #53
