### ISSUE TITLE
Right Click hook providing Marker

### ISSUE THREAD

**Issue by atltt** [utk-cs/team-minsky#55]
This better be in TS Brian or there will be hell to pay.

Also @robobenklein is this what you were mentioning yesterday?

**Comment by robobenklein** [comment]
This is not quite what I meant, one sec...

**Comment by robobenklein** [comment]
On right-click, we should add a context item to `Marker`s that we have identified to be issue tags.

Markers will be placed by the regex filter from #54 once I'm done with that, then you will just need to detect the right click, determine if there is a compatible marker there, and if so, then add the context menu item to show a "Open/Show Issue" option which we then need to link to the hover, drawer, or pane views.

**Comment by atltt** [comment]
I'm just gonna throw this into my cool little hover nonsense

hoverMain.js GROWS STRONGER

**Comment by atltt** [comment]
Duplicate so I am closing
