### ISSUE TITLE
Split feature branches: Rex/newPanel vs newPanelView

### ISSUE THREAD

**Issue by robobenklein** [utk-cs/team-minsky#63]
Boo! Split features are bad! Get these organized and tracked back to eachother!

**Comment by robobenklein** [comment]
@atltt @RexRascerX 

Neither of these got in, see if there's anything we need from them and then delete them once no longer needed.

**Comment by robobenklein** [comment]
Also idk why they were both called `Panel` when we were making `Pane`s

**Comment by RexRascerX** [comment]
Call it a typo. Since we aren't using them anymore, I have no need for my work.

**Comment by atltt** [comment]
Will close
