### ISSUE TITLE
Set up Atom plugin package layout

### ISSUE THREAD

**Issue by ilumsden** [utk-cs/team-minsky#8]
We need to set up the package layout so that we can eventually publish our plugin.

Atom has a built-in way of setting it up initially, so we just need to figure out if there are any changes we have to make.

**Comment by robobenklein** [comment]
Linking #19 because that's probably where we'll get the best TS plugin layout from.

**Comment by robobenklein** [comment]
We did it

![image](https://user-images.githubusercontent.com/5423266/45841592-43291300-bce8-11e8-92a9-e83229eaf231.png)
