### ISSUE TITLE
Decide on a design for the plugin

### ISSUE THREAD

**Issue by ilumsden** [utk-cs/team-minsky#9]
We need to decide what we want the final plugin to look like so that we can get started on CSS and HTML coding.

**Comment by robobenklein** [comment]
Alright I thought of a much better design for the embedded issues than a popover.

Instead, the GH#ISSUEID label will have a dropdown arrow that will expand a small issue window (like 5-20 LOC) directly in between the existing code where the issue was referenced.

Will have a new mockup soon.

**Comment by robobenklein** [comment]
![screenshot from 2018-09-13 16-40-13](https://user-images.githubusercontent.com/5423266/45520243-7880ae80-b786-11e8-9181-fcadc67205ca.png)

very rough, but that is approx the layout

**Comment by ilumsden** [comment]
It might still be a good idea to include an expansion to a larger view if we have time. That way, we could include functionality that may be hard to fit in the limited space.

**Comment by robobenklein** [comment]
I plan on having the drawer be resizable, should we still have it be able to popout into it's own pane/panel?

I think that's doable both ways, we should have enough hands on code to do everything: drawer, pane, and hover-over.
